executable=/afs/cern.ch/user/g/gdamolin/Johan/TTbar/RunDataset.sh

#add path to every executable ( we are doing cd in Prescript)

+PreCmd="/afs/cern.ch/user/g/gdamolin/Johan/TTbar/PreScript.sh"

#+PostArguments=$(ClusterId)
#+PostCmd=/afs/cern.ch/user/g/gdamolin/Johan/TTbar/PostScript.sh


output                = output/hello.$(ClusterId).$(ProcId).out
error                 = error/hello.$(ClusterId).$(ProcId).err
log                   = log/hello.$(ClusterId).log

+JobFlavour="tomorrow"
queue transfer_input_files, arguments from (
  /afs/cern.ch/user/g/gdamolin/Johan/TTbar/script.txt,/afs/cern.ch/user/g/gdamolin/Johan/TTbar/script.txt
  )
