#se facessi uno script che fa condo_submit con argomenti diversi e uso come eseguibile uno script che semplicemente crea l'environment e chiama il .cc?"
executable ="run_MC.sh"
arguments= $1

output="/eos/user/g/gdamolin/TT2bbemu/output"
error="/eos/user/g/gdamolin/TT2bbemu/error"
log="/eos/user/g/gdamolin/TT2bbemu/log"

#initialdir=""
+JobFlavour="tomorrow"
transfer_output_files=""

#potrei fare uno script che fa già hadd
#+PostCmd=""
queue 1
