executable=$1
#executable=/afs/cern.ch/user/g/gdamolin/CMSSW_12_4_1_patch1/src/Johan/TTbar/Mixed_Analysis

getenv      = True
environment = "/afs/cern.ch/user/g/gdamolin/CMSSW_12_4_1_patch1/src/Johan/TTbar"

transfer_input_files= /afs/cern.ch/user/g/gdamolin/private/x509up_u151129
arguments= $2 $3 $4 $5 $6

#arguments= root://cms-xrd-global.cern.ch//store/mc/RunIISummer20UL18NanoAODv2/DYJetsToLL_1J_TuneCP5_13TeV-amcatnloFXFX-pythia8/NANOAODSIM/106X_upgrade2018_realistic_v15_L1v1-v1/130000/6E2A3FD3-C3FD-5A4C-B97C-58DC2C0A0A60.root /eos/user/g/gdamolin/TT2bbemu/DY1/6E2A3FD3-C3FD-5A4C-B97C-58DC2C0A0A60_MA.root 951.5*1000 59.83 False

output                = /afs/cern.ch/user/g/gdamolin/Johan/output/hello.$(ClusterId).$(ProcId).out
error                 = /afs/cern.ch/user/g/gdamolin/Johan/error/hello.$(ClusterId).$(ProcId).err
log                   = /afs/cern.ch/user/g/gdamolin/Johan/log/hello.$(ClusterId).log

queue 
