executable=/afs/cern.ch/user/g/gdamolin/Johan/TTbar/Mixed_Analysis

transfer_input_files= /afs/cern.ch/user/g/gdamolin/private/x509up_u151129, /afs/cern.ch/user/g/gdamolin/Johan/CheapTrick/myfile.txt


output                = /afs/cern.ch/user/g/gdamolin/Johan/output/hello.$(ClusterId).$(ProcId).out
error                 = /afs/cern.ch/user/g/gdamolin/Johan/error/hello.$(ClusterId).$(ProcId).err
log                   = /afs/cern.ch/user/g/gdamolin/Johan/log/hello.$(ClusterId).log

queue arguments from (
 /afs/cern.ch/user/g/gdamolin/Johan/CheapTrick/myfile.txt
)
